/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.hepl.java_mail.GUI;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Header;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.internet.MimeUtility;

/**
 *
 * @author student
 */
public class OpenMoreInfoMail extends javax.swing.JDialog {
    
    // <editor-fold defaultstate="collapsed" desc="Constructors">
    /**
     * Creates new form MoreInfoMail
     * @param parent
     * @param modal
     * @param headers
     * @param subject
     * @throws javax.mail.MessagingException
     */
    public OpenMoreInfoMail(java.awt.Frame parent, boolean modal, ArrayList<Header> headers, String subject) throws MessagingException {
        super(parent, modal);
        initComponents();
        
        this.setTitle(subject);
        
        //Affichage des headers:
        String txt = "";
        int i = 1;
        for(Header h : headers){
            txt += "======================= HEADER "+ i +" ============================\n";
            
            try {
                txt += h.getName() + " =\n  ";
                txt += MimeUtility.decodeText(h.getValue()) + "\n";
            } catch (UnsupportedEncodingException ex) {
                txt += "Not a String Header";
                Logger.getLogger(OpenMoreInfoMail.class.getName()).log(Level.SEVERE, null, ex);
            }           
            
            txt += "======================= FIN HEADER "+ i +" ============================\n\n\n\n";
            i++;
        }
        
        this.headers.setText(txt);
    }
    // </editor-fold>    
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        headers = new javax.swing.JTextArea();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Headers:");

        headers.setColumns(20);
        headers.setLineWrap(true);
        headers.setRows(5);
        headers.setWrapStyleWord(true);
        jScrollPane1.setViewportView(headers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Property">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea headers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
