/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package be.hepl.payement_client.GUI;

import be.hepl.payement_protocol.Utils.Gestion_Protocol_Client;
import be.hepl.payement_protocol.model.Facture;
import be.hepl.payement_protocol.model.Sale;
import java.awt.Frame;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sirac
 */
public class BillPage extends javax.swing.JDialog {

    // <editor-fold defaultstate="collapsed" desc="My Properties">
    private final Facture bill;
    private final Gestion_Protocol_Client GPC;
    private final Frame owner;
    private boolean payed;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Constructors">
    /**
     *
     * @param bill
     * @param owner
     * @param title
     * @param modal
     */
    public BillPage(Gestion_Protocol_Client GPC, Facture bill, Frame owner, String title, boolean modal) {
        super(owner, title, modal);
        initComponents();
        
        this.setTitle(title);
        
        this.bill = bill;
        this.GPC = GPC;
        this.owner = owner;
        
        this.IdFacture_Textfield.setText("" + bill.getId());
        this.Date_Textfield.setText("" + bill.getDate());
        this.NomClient_Textfield.setText("" + bill.getIdClient());
        
        DecimalFormat df = new DecimalFormat("#.##");
        this.PrixTotal_TextField.setText("" + df.format(bill.getPrix()));
        
        payed = bill.isPayed();
        this.Payer_Button.setEnabled(!payed);
        RefreshUI();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Methods">
    public void RefreshUI()
    {
        DecimalFormat df = new DecimalFormat("#.##");       
        DefaultTableModel model = (DefaultTableModel) this.Sales_Table.getModel();
        model.setRowCount(0);
        
        for(Sale sale : bill.getSales()){
            Vector<Object> rowData = new Vector<>();
            
            rowData.add(sale.getIntitule());
            rowData.add(sale.getQuantiteVendue());
            rowData.add(df.format(sale.getPrixUnite()));
            rowData.add(df.format((float)sale.getQuantiteVendue() * sale.getPrixUnite()));
            
            model.addRow(rowData);
        }
    }
    // </editor-fold>
        
    // <editor-fold defaultstate="collapsed" desc="Generated code">
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        NomClient_Textfield = new javax.swing.JTextField();
        IdFacture = new javax.swing.JLabel();
        Payer_Button = new javax.swing.JButton();
        Annuler_Button = new javax.swing.JButton();
        IdFacture_Label = new javax.swing.JLabel();
        IdFacture_Textfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sales_Table = new javax.swing.JTable();
        Date_Textfield = new javax.swing.JTextField();
        PrixTotal_TextField = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bill");
        setMinimumSize(new java.awt.Dimension(558, 475));

        NomClient_Textfield.setFocusable(false);

        IdFacture.setText("Nom Client :");

        Payer_Button.setText("Payer");
        Payer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Payer_ButtonActionPerformed(evt);
            }
        });

        Annuler_Button.setText("Retour");
        Annuler_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annuler_ButtonActionPerformed(evt);
            }
        });

        IdFacture_Label.setText("Id facture :");

        IdFacture_Textfield.setFocusable(false);

        Sales_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Intitulé", "Quantité", "Prix Unitaire", "Prix total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Sales_Table.setFocusable(false);
        Sales_Table.setRequestFocusEnabled(false);
        Sales_Table.setRowSelectionAllowed(false);
        Sales_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Sales_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Sales_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Sales_Table);

        Date_Textfield.setFocusable(false);

        PrixTotal_TextField.setText("0.0");
        PrixTotal_TextField.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PrixTotal_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdFacture)
                            .addComponent(IdFacture_Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomClient_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IdFacture_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Date_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Payer_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Annuler_Button)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdFacture_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdFacture_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomClient_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrixTotal_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annuler_Button)
                    .addComponent(Payer_Button))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Events">
    private void Annuler_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annuler_ButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Annuler_ButtonActionPerformed

    private void Payer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Payer_ButtonActionPerformed
        PayementPage window = new PayementPage(GPC, bill, this.owner, ("Payement Bill["+bill.getId()+"] - " + bill.getDate()), true);
        window.setVisible(true);
        
        this.Payer_Button.setEnabled(!window.payed);
    }//GEN-LAST:event_Payer_ButtonActionPerformed
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Generated Properties">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler_Button;
    private javax.swing.JTextField Date_Textfield;
    private javax.swing.JLabel IdFacture;
    private javax.swing.JLabel IdFacture_Label;
    private javax.swing.JTextField IdFacture_Textfield;
    private javax.swing.JTextField NomClient_Textfield;
    private javax.swing.JButton Payer_Button;
    private javax.swing.JTextField PrixTotal_TextField;
    private javax.swing.JTable Sales_Table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}

